### ISSUE TITLE
Keybow crashes if key pressed when computer is not running

### ISSUE THREAD

**Issue by dgdguk** [sandyjmacdonald/keybow2040-circuitpython#10]
I've observed that if the Keybow is powered but the computer it's attached to is not running, then the Keybow will crash. This is because in the depths of circuitpython, the send_report function will timeout, which will raise an Exception (I think an OSError, but not sure), which won't be caught, thus crashing the Keybow. That's not ideal.

I've hacked together a fix, but this repository seems somewhat abandoned, so I'd like to get confirmation that it's alive before putting some effort into tidying it up and submitting it as a patch.

**Comment by brandoningli** [comment]
I'm also experiencing this and would love to see what you've got as a patch!

**Comment by dgdguk** [comment]
The code I've got is not great, as in I'm sure that someone familiar with `adafruit_hid.keyboard` could trivially come up with a better solution. It's also not really a patch at the moment, because it is literally just catching the exception raised by `keyboard.send`, which in this library is in user supplied code.

I suppose one could substitute `keyboard.send` with the following function:

```python
def safe_send(keyboard, keycode):
  """Catches errors from keyboard.send. Returns true if no error raised, false otherwise"""
  try:
    keyboard.send(keycode)
    return True
  except:
    return False
```

But this is still what I'd call quite suboptimal as in this case it will wait 5 seconds for `keyboard.send` to time out.

**Comment by Gadgetoid** [comment]
This repository will hopefully be replaced by - https://github.com/pimoroni/pmk-circuitpython

All of our stuff looks abandoned because I'm juggling about 200 projects and by the time I come back around to something it's been two years :cry:
