### ISSUE TITLE
BOOTSEL button as user input

### ISSUE THREAD

**Issue by PCHSwS** [sandyjmacdonald/keybow2040-circuitpython#11]
While 16 buttons are a lot for macro actions, in my use case I've maxed out and used every single one of them. It would be awesome to be able to use the BOOTSELbutton as a quick way to turn off the lights (for example, or trigger other actions), but it doesn't seem to be mapped in this library. Can someone point out to me, what I have to change to get that, or maybe it could be even implemented here? I'm sure some users could benefit from it.
Thanks!

**Comment by JDR11** [comment]
In terms of needing more actions, circuitpython has functionality to support layers. This would allow you to effectively have multiple pages of keys available.

**Comment by Gadgetoid** [comment]
IIRC the bootsel button is possible to read from CircuitPython so this is worth exploring. Though telling it apart from reset might require some practice :grimacing: 

If you're still angling for us to look into this, could you re-raise over at https://github.com/pimoroni/pmk-circuitpython where I plan to continue development.

Thank you!
