### ISSUE TITLE
keybow 2040 keyboard library problem 

### ISSUE THREAD

**Issue by cfgomez83** [sandyjmacdonald/keybow2040-circuitpython#13]
If this is the wrong place to raise this issue then please close it and tell me where I should go.

When I tried to upgrade my Keybow 2040 to the latest software, the "from adafruit_hid.key[...anything...]" dependencies broke.  The reactive-press.py and rainbow.py still work fine, but the hid-key*.py do not work,  I can no longer use the keybow 2040 as a keyboard.

I downloaded these versions :

https://circuitpython.org/board/pimoroni_keybow2040/
md5sum = 87d600d81cbe0d5590868b3b74f3f0d1 *adafruit-circuitpython-pimoroni_keybow2040-en_US-7.0.0.uf2

...
File: boot_out.txt :
Adafruit CircuitPython 7.0.0 on 2021-09-20; Pimoroni Keybow 2040 with rp2040
Board ID:pimoroni_keybow2040
...

https://github.com/adafruit/Adafruit_CircuitPython_IS31FL3731
md5sum = e1038d6621566df25c6baa831d105e94 *Adafruit_CircuitPython_IS31FL3731-main.zip

...
commit 06896940f91b8b0084d0a100f38398a02280ce16
Date:   Tue Nov 23 13:03:03 2021 -0600
...

https://github.com/pimoroni/keybow2040-circuitpython
md5sum = 0f7540daf9aa6a260fa49b3fae8835a1 *keybow2040-circuitpython-master.zip

...
commit 7770d336e79101636029c958d0b9368686017df5
Date:   Fri Nov 5 15:45:45 2021 +0000
...

This issue may be an error on my part but I would like to request a table of the different software versions that were tested together.  I want to "sync" my keybow 2040 to known compatible sofware versions. If I had this then it would place the onus on me to make sure I am doing everything correctly.

Thank you for all the hard work everyone put into this.

**Comment by helgibbons** [comment]
If you're running CircuitPython 7 on your Keybow, you'll need to make sure you have the matching CircuitPython 7 versions of the libraries present in your `lib` folder - sounds like you might be missing the updated `adafruit_hid` library?

You can download it here: https://github.com/adafruit/Adafruit_CircuitPython_HID (or download the CP7 library bundle that includes them all: https://circuitpython.org/libraries )

**Comment by cfgomez83** [comment]
You are correct, I failed to update the libraries.  After I downloaded the CP7 library bundle (adafruit-circuitpython-bundle-7.x-mpy-20211220.zip) and replaced the adafruit_hid folder, the keyboard worked again.

Thank You, and Happy Holidays!
